-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
JOIN DOCTOR d
ON d.DR_ID = a.MDDR_ID
JOIN PATIENT p
ON p.PT_NO = a.PT_NO
where a.APNT_CNCL_YMD IS NULL
AND a.MCDP_CD = 'CS'
AND a.APNT_YMD >= '2022-04-13'
AND a.APNT_YMD < '2022-04-14'
ORDER BY a.APNT_YMD;